---
name: CGI-Application-Plugin-Config-Context
version: 0.18
author:
  - Michael Graham <mag-perl@occamstoothbrush.com>
abstract: 'Hierarchical, context-based configuration support for CGI::Application'
license: perl
requires:
  CGI::Application: 0
  Config::Context: 0.06
  Test::More: 0
provides:
  CGI::Application::Plugin::Config::Context:
    file: lib/CGI/Application/Plugin/Config/Context.pm
    version: 0.18
generated_by: Module::Build version 0.2611
